# -*- coding: utf-8 -*-
"""first.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWKXFDfs1te1-qzT3f4pOc_lcFR2xey0
"""

print("Hello world!")

print("Hello", "World!", sep=" ")

print("Hello",end=" ")
print("World!")

digit=True
print(digit)
print(type(digit))

s=input()
print(s)

name=input("Enter your name: ")
print("Welcome ", name)
print(type(name))

age=int(input("Enter your age: "))
print(age)
print(type(age))

a=200
b=300
sum=a+b
print(sum)

diff=b-a
print(diff)

pro=a*b
print(pro)
ratio=a/b
print(ratio)
rem=a%b
print(rem)
quo=a//b
print(quo)